modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "xaeroplus"
version = "1.20.1"
displayName = "XaeroPlus"
authors = "rfresh2"
description = '''
Xaero WorldMap / Minimap Extra Features
'''
logoFile = "icon.jpg"

[[dependencies.xaeroplus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xaeroplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xaeroplus]]
modId = "xaerominimap"
mandatory = true
versionRange = "[23.5.0]"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.xaeroplus]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "[1.30.6]"
ordering = "BEFORE"
side = "BOTH"
