name: Forge 1.12.2 Build And Release

on:
  push:
    branches:
      - "mainline"
env:
  WORLDMAP_VERSION: "1.30.5"
  MINIMAP_VERSION: "23.5.0"
  MINECRAFT_VERSION: "1.12.2"
  MINECRAFT_VERSION_SHORT: "1.12"
  MOD_LOADER: "Forge"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Elevate wrapper permissions
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Rename built mod
      run: mv build/libs/xaeroplus-${{ env.MINECRAFT_VERSION }}.jar XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}
        path: XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar

    - name: Download Xaero WorldMap
      run: wget https://chocolateminecraft.com/mods2/worldmap/XaerosWorldMap_${{ env.WORLDMAP_VERSION }}_${{ env.MOD_LOADER }}_${{ env.MINECRAFT_VERSION_SHORT }}.jar --no-check-certificate

    - name: Download Xaero Minimap
      run: wget https://chocolateminecraft.com/mods2/minimap/Xaeros_Minimap_${{ env.MINIMAP_VERSION }}_${{ env.MOD_LOADER }}_${{ env.MINECRAFT_VERSION_SHORT }}.jar --no-check-certificate

    - name: Create modpack zip
      run: >
        tar -czvf 
        XaeroPlus-modpack-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}.zip 
        XaeroPlus-${{ env.MOD_LOADER }}-${{ env.MINECRAFT_VERSION }}-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}.jar 
        XaerosWorldMap_${{ env.WORLDMAP_VERSION }}_${{ env.MOD_LOADER }}_${{ env.MINECRAFT_VERSION_SHORT }}.jar 
        Xaeros_Minimap_${{ env.MINIMAP_VERSION }}_${{ env.MOD_LOADER }}_${{ env.MINECRAFT_VERSION_SHORT }}.jar

    # todo: for future auto-update check feature
#    - name: Create version identifier file
#      run: echo ${{ github.run_number }} > version.txt

    - name: Release
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        curseforge-id: 866084

        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-id: EnPUzSTg

        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-files: |
          xaeroplus-*.jar
          xaeroplus-modpack-*.zip

        files: |
          xaeroplus-*.jar
        name: xaeroplus-${{ github.run_number }}-WM${{ env.WORLDMAP_VERSION }}-MM${{ env.MINIMAP_VERSION }}
        version: ${{ github.run_number }}
        loaders: |
          ${{ env.MOD_LOADER }}
        game-versions: |
          ${{ env.MINECRAFT_VERSION }}
        dependencies: |
          xaerominimap@${{ env.MINIMAP_VERSION }}(required){modrinth:1bokaNcj}{curseforge:263420}
          xaeroworldmap@${{ env.WORLDMAP_VERSION }}(required){modrinth:NcUtCpym}{curseforge:317780}
